language: c

env:
    - TEST=autoconf
    - TEST=make

branches:
    only: travis

script:
    - if [ x$TEST = xautoconf ]; then ./autogen.sh && ./configure; fi
    - make && make test && sudo make install

notifications:
    recipients:
        - lcd047@gmail.com
