language: c

env:
    - TEST=autoconf
    - TEST=make

install:
    - if [ x$TEST = xautoconf ]; then ./autogen.sh && ./configure; fi

script:
    - make
    - make test

notifications:
    recipients:
        - lcd047@gmail.com
