language: c

env:
    - TEST=autoconf
    - TEST=make

branches:
    only: travis

install:
    - if [ x$TEST = xautoconf ]; then ./autogen.sh && ./configure --prefix=$HOME; fi

script:
    - make
    - make test
    - make install

notifications:
    recipients:
        - lcd047@gmail.com
